
CREATE TABLE transtats_city_origin AS
        SELECT origin_airport_id, ORIGIN_AIRPORT_SEQ_ID, ORIGIN_CITY_MARKET_ID, ORIGIN, origin_city_name, ORIGIN_STATE_ABR, ORIGIN_STATE_NM, ORIGIN_WAC
        FROM transtats
        GROUP BY origin_airport_id, ORIGIN_AIRPORT_SEQ_ID, ORIGIN_CITY_MARKET_ID, ORIGIN, origin_city_name, ORIGIN_STATE_ABR, ORIGIN_STATE_NM, ORIGIN_WAC;

ALTER TABLE transtats_city_origin ADD PRIMARY KEY (origin_airport_id);

ALTER TABLE transtats DROP COLUMN ORIGIN_AIRPORT_SEQ_ID;
ALTER TABLE transtats DROP COLUMN ORIGIN_CITY_MARKET_ID;
ALTER TABLE transtats DROP COLUMN ORIGIN;
ALTER TABLE transtats DROP COLUMN origin_city_name;
ALTER TABLE transtats DROP COLUMN ORIGIN_STATE_ABR;
ALTER TABLE transtats DROP COLUMN ORIGIN_STATE_NM;
ALTER TABLE transtats DROP COLUMN ORIGIN_WAC;